### ISSUE TITLE
Can't uninstall/fix/use azure sphere sdk

### ISSUE THREAD

**Issue by Niproblema** [MicrosoftDocs/azure-sphere-issues#133]
uninstaller hangs at azure sphere services
See probably same issue https://social.msdn.microsoft.com/Forums/en-US/88aa78d4-2840-4b8f-a1c2-d5cfa2578c16/azure-sphere-sdk-will-not-uninstall-my-solution?forum=azuresphere

**Comment by Niproblema** [comment]
Log file 
[dd_VC_AzureSphere_20190812100304.log](https://github.com/MicrosoftDocs/azure-sphere-issues/files/3491438/dd_VC_AzureSphere_20190812100304.log)

**Comment by AshokPeddakotla-MSFT** [comment]
@Niproblema Please help with the link of document on which above document feedback request is created.
In case your query in not related to document content, open a new forum thread in MSDN forum or Stack Overflow as it could be better place to get help on your scenario. 
These forum community members could provide their expert guidance on your scenario based on their experience.
Thanks!

**Comment by Alberto-Vega-MSFT** [comment]
@Niproblema Do you have an update?

**Comment by Niproblema** [comment]
What am I supposed to update you on?
Issue is known and solution is known, next step would be to implement fix.

**Comment by Alberto-Vega-MSFT** [comment]
Hi @Niproblema We were asking for a link to a document to tie this issue to since the issues on this repository are meant for documentation errors or suggestions on documentation enhancements. With that said.

I see that unlike other customer (on the thread you linked to) uninstall is failing for you. We need to get you help from support engineers. If you do not have access to a support plan, please reach out @ AZCommunity@microsoft.com with a link to this Doc/Issue as well as your subscription ID and we can help get a one time free support ticket opened for this issue.

**Comment by Alberto-Vega-MSFT** [comment]
@Niproblema please reach out to the email I provided on my previous comment so we can get you a one time free support ticket if you don't have a  support plan. Closing this issue now since a support engineer will assist you now.
