### ISSUE TITLE
 [loc][Query][vscode-azure-sphere-tools] Localizability of string: 0; "package.azure-sphere-tools.azurespheredbg.launch.setupCommands.description"

### ISSUE THREAD

**Issue by PDostalek** [MicrosoftDocs/azure-sphere-issues#211]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
One or more GDB commands to execute in order to setup the underlying debugger. Example: "setupCommands": [ { "text": "-enable-pretty-printing", "description": "Enable GDB pretty printing", "ignoreFailures": true }].

File:
Src\vscode-extensions\vscode-azure-sphere-tools.xlf

Query:
Should we localize "Enable GDB pretty printing"?

**Comment by MarileeTurscak-MSFT** [comment]
@PDostalek please provide the link to the document which you are following so that we can better assist.

**Comment by AshokPeddakotla-MSFT** [comment]
@PDostalek Please help with the link of document on which above document feedback request is created. 
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by AshokPeddakotla-MSFT** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.

In case your query is not related to document content, open a new forum thread in [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/newthread?prof=required) or [Stack Overflow](https://stackoverflow.com/) as it could be better place to get help on your scenario. 
These forum community members could provide their expert guidance on your scenario based on their experience. Thanks.
