### ISSUE TITLE
Cannot login in my account

### ISSUE THREAD

**Issue by michalmar** [MicrosoftDocs/azure-sphere-issues#224]
I have followed these steps and everything went ok ( got my account/tennant and device claimed). But when I try to login (after couple of days) I am getting error on `azsphere login` - login failed (i am using my microsoft account which is working). Is there a way to troubleshoot that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a777684-ac8f-25df-600d-4b8aafada22a
* Version Independent ID: 8889f26b-3adf-1b14-f523-2f9844b82a2c
* Content: [Claim your device - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/claim-device#feedback)
* Content Source: [AzureSphere/articles/install/claim-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/claim-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@michalmar Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@michalmar  After updating your windows 10 to the latest version your issue is resolved. We will further look into this issue and share more updates if any. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
