### ISSUE TITLE
Board configuration still ONLY refers to ISU0 and INT5 

### ISSUE THREAD

**Issue by Gerriko** [MicrosoftDocs/azure-sphere-issues#239]
[Enter feedback here]

I believe almost 1 year ago it was highlighted that some other Azure Sphere boards use ISU1 and thus the package described in this document was incorrect (Microsoft supplies a board configuration for the Microchip ENC286J60 Ethernet chip, which must be attached via SPI to ISU0 with interrupts on GPIO5. )

If you are not going to provide a similar package for ISU1, please could you add in a link on this page to direct the user to the relevant information so that they can develop their own package. At the moment the document appears to say to me that if you happen to have hardware that uses ISU1 for SPI then there is no chance you can add in Ethernet.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3781077-8806-0de8-85c1-a0e08b3abe8c
* Version Independent ID: f53b30fb-3874-c03e-bb5e-ab194b15fc53
* Content: [Connect Azure Sphere to Ethernet](https://docs.microsoft.com/en-us/azure-sphere/network/connect-ethernet)
* Content Source: [AzureSphere/articles/network/connect-ethernet.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/network/connect-ethernet.md)
* Product: **azure-sphere**
* GitHub Login: @Phka
* Microsoft Alias: **azurespheredocs**

**Comment by errohitsinghal** [comment]
I am waiting for a response to this item. Deployment of Azure Sphere devices on the field is just so difficult that I am almost about to drop this for any of my future commercial projects. There is absolutely no way (at least in my knowledge) to deploy Sphere devices on the field since we can't allow end-user to configure WiFi on-site and ethernet connectivity is not flexible with different boards. Adding multiple custom ImagePackage will really help a lot in having Ethernet connectivity so for the first-use Ethernet Cable can be plugged in and device-provisioning can be triggered. Adding WiFi Access Point capability is equally important if this device is meant for commercial projects other than DIY.

**Comment by SatishBoddu-MSFT** [comment]
@Gerriko @errohitsinghal 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment]
@errohitsinghal Just quoting your previous comment on past github issue. Please confirm if todays comment is related to the past comment ?

Old comment  : https://github.com/MicrosoftDocs/azure-sphere-issues/issues/114#issuecomment-521805275

**Comment by errohitsinghal** [comment]
@SatishBoddu-MSFT Yes Satish, that's related.

**Comment by SatishBoddu-MSFT** [comment]
@Gerriko Could you please share your business impact or any customer impact from the current package ? We wanted to collect best justification for developing own package in this matter.

On the below suggestion we will get back to you soon.

> If you are not going to provide a similar package for ISU1, please could you add in a link on this page to direct the user to the relevant information so that they can develop their own package. At the moment the document appears to say to me that if you happen to have hardware that uses ISU1 for SPI then there is no chance you can add in Ethernet.

**Comment by SatishBoddu-MSFT** [comment]
> @SatishBoddu-MSFT Yes Satish, that's related.

@errohitsinghal Thanks for confirming, Could you also please share your business impact or any customer impact from the current design ? 

Also in the past there were suggestions on Ethernet head usage, does those help in any way, want your feedback on those suggestions ..../

**_To recollect the past suggestions, .._**

**Reference MSDN thread**: [Avnet Azure Sphere Starter Kit does not work with the Ethernet examples (new hardware configuration build required)](https://social.msdn.microsoft.com/Forums/en-US/e4b57de0-63ef-4f13-9da2-74fa0cbda330/avnet-azure-sphere-starter-kit-does-not-work-with-the-ethernet-examples-new-hardware-configuration?forum=azuresphere)

Quote:https://github.com/MicrosoftDocs/azure-sphere-issues/issues/114#issuecomment-547351948
> if it helps, please note that other Azure Sphere dev kits support hard-wired Ethernet. In particular, the Seeed MT3620 dev kit has an Ethernet shield available.

**Comment by errohitsinghal** [comment]
Hi Satish,

Thanks for follow up on this. Here are the details about business impact, 

**Background:** We have a few customers who heavily use IOT technologies since they are in Cement, Transmission Wire domains with large manufacturing units and IoT is the best fit. We have already deployed around ~800 IOT units based on AVR on the field in the last 5 years

**Business Case:** Due to MOU/NDA signed specific details can't be shared but at a high level, we faced multiple security issues in last years with AVR devices and we had two options, design our own secured IoT Suite or switch to Azure Sphere. The customer wanted a real quick turnaround so we decided to proceed with Avnet based starter Kit. Avnet starter kit is designed with great engineering. hardware wise it supplies everything we needed. We procured and deployed our project based on Avnet Starter Kit and later realized that the WiFi Noise filter on Azure Sphere is not so efficient and performance is poor on the noisy networks (Apparently its a known issue). As you understand, Deploying a new dedicated wifi network in a large area (~10K SqFt) is not a feasible option so we wanted to add Ethernet Capability in our existing devices but we are stuck since Image Package is not available. Since this whole ecosystem is a closed source, we are kind of at the mercy of Microsoft Support. We can use Seed-Studio kit or some other kit but we'll have to accept in front of the customer that Microsoft hasn't supported this platform that's why we want to re-implement the solution but that's what we pitched while implementation that its Microsoft Backed! In that case, we'll drop the entire Azure suite and move to the traditional device ecosystem. 

apart from this, Avnet is one of the major partners in implementing Azure Sphere. They might have sold many thousands (maybe millions) units of Azure Sphere SK. Nonavailibity of alternate Image-Package seems like a compatibility issue with Sphere OS and should be resolvable with Software. Ethernet Connectivity is still common in Industrial Applications and leaving those thousands of enthusiast developers who received Avnet Kit without an important option might kill the interest for many for a great product like Azure Sphere. This is a kind of first device having end-to-end IoT security at such ease, please consider issues industry/startup is facing while deploying them commercially so it becomes the first choice in a competitive market.

**Comment by SatishBoddu-MSFT** [comment]
Thank you @errohitsinghal for sharing in-depth details, we are currently working on this part, will share outcome from our side. We have already discussed the [same topic](https://github.com/MicrosoftDocs/azure-sphere-issues/issues/114) in the past, as we quoted in our previous comments. 

Could you please also confirm if using any[ Ethernet shield](https://github.com/MicrosoftDocs/azure-sphere-issues/issues/114#issuecomment-547351948) helped in your scenario?

**Comment by SatishBoddu-MSFT** [comment]
Hello @Gerriko Just checking back, could you please share your use case scenario & Impacts as well, we are trying our best to collect all feature requests, so that we come up with a healthy discussion outcome on this topic.

**Comment by Gerriko** [comment]
No, fortunately I discovered that in my case it was user-error as my Azure
sphere device did in fact use ISU0 for SPI. It was through my research that
I discovered that some Azure Sphere devices use ISU1 for SPI and yet the
official documentation makes no mention of what to do if you did have such
a device. Hence the reason for raising the issue.

**Comment by SatishBoddu-MSFT** [comment]
Hello @Gerriko, Thanks for the info, could you please let us know the type of Azure Sphere device you are using , so that we take a look at the documentation part.

**Comment by Gerriko** [comment]
The documentation is fine for my product, which is the Azure Sphere
Guardian 100, but for completeness the document lacks explanation on what
to do if ISU1 SPI is required.

**Comment by SatishBoddu-MSFT** [comment]
Just adding a quick reference link of the device: [Azure Sphere Guardian-100](https://www.avnet.com/opasdata/d120001/medias/docus/197/5372-PB-AES-MS-MT3620-GUARD-100-V1-v3a%20(1).pdf)

**Comment by pennyo** [comment]
@Gerriko We do not currently have a way to create your own custom board configurations, nor to specify that a different ISU should be used. You can raise this as a feature request in the [Azure Sphere forum](https://feedback.azure.com/forums/915433-azure-sphere).
