### ISSUE TITLE
wolfssl inclusion

### ISSUE THREAD

**Issue by kiranpradeep** [MicrosoftDocs/azure-sphere-issues#244]
Can wolfssl header files documentation be included here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9800cae8-dfe3-2903-0990-ae90b3fa38a1
* Version Independent ID: a79b06c0-38e8-6ab1-9c6b-27da5171db4a
* Content: [Azure Sphere Application Libraries reference](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/api-overview)
* Content Source: [AzureSphere/articles/reference/applibs-reference/api-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/api-overview.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@kiranpradeep Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
There is a separate doc available for wolf SSL here: https://docs.microsoft.com/en-us/azure-sphere/app-development/wolfssl-tls
Since this is not a mandatory update we will consider this for our future updates. Adding author @pennyo for further review and update the doc if necessary. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
