### ISSUE TITLE
azsphere product update example needs ", not '

### ISSUE THREAD

**Issue by daesma** [MicrosoftDocs/azure-sphere-issues#255]
azsphere product update --productid b053aefe-b60d-4420-bf28-f55c69c4446e --newname DW100Product --newdescription 'Contoso DW100 models'
Unrecognized command line argument 'DW100'.
Unrecognized command line argument 'models''.

example on page needs to change from
azsphere product update --productid b053aefe-b60d-4420-bf28-f55c69c4446e --newname DW100Product --newdescription 'Contoso DW100 models'

to 
azsphere product update --productid b053aefe-b60d-4420-bf28-f55c69c4446e --newname DW100Product --newdescription "Contoso DW100 models"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 182117ef-f951-73b2-1632-ac917789df3f
* Version Independent ID: 005310ee-e514-4e9f-0c6f-c92a45c199c6
* Content: [Azure Sphere CLI product command](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-product)
* Content Source: [AzureSphere/articles/reference/azsphere-product.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/azsphere-product.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by SatishBoddu-MSFT** [comment]
Hello @daesma 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment]
Hello @daesma Thank you reporting this. We will update the document soon.

**Issue**: Updates specified product metadata , CLI Command --_newdescription_  needs **Double Quotes** instead of **single quotes**

![image](https://user-images.githubusercontent.com/62923178/93043743-a021e000-f607-11ea-8465-4697839c0f9a.png)


[update](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-product#update)

![image](https://user-images.githubusercontent.com/62923178/93043883-fb53d280-f607-11ea-9045-f8ff30247ee8.png)
