### ISSUE TITLE
Azure Sphere - Tenant Registration Issues on Ubuntu

### ISSUE THREAD

**Issue by nk-gears** [MicrosoftDocs/azure-sphere-issues#258]
Background :
- I am Mac developer. I thought of trying Azure Sphere and Bought one in 2019 (Azure Sphere MT3620 Starter Kit)
- At that time the only Supported OS is Windows 10. So, i installed Virtual Box and successfully able to connect the Starter Kit and Registered the tenant. 
- Then i wanted to run few programmes and i thought i will wait for support for Ubuntu and then start actively using this.

Later this month, I opened the Azure Sphere and connected to a Ubuntu and i was getting a weird error. Tenant not found. If i try to create one its saying the device is already claimed in a different tenant.

I was spending long hours and i could not find any relevant information other than the similar thread.  https://docs.microsoft.com/en-us/answers/questions/57338/azure-sphere-tenant-not-found.html

Then i used device recover command. After this, the device is no more recognized.

Would like to give a final attempt before i dispose this starter kit. I mean i want to know whether i corrupted the device or its the SDK Version conflict between the Windows 10 and Ubuntu SDK.

Can someone help me on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1dfe8d-03d1-28ec-6155-6560a12fabce
* Version Independent ID: 25def8b1-7c70-e84c-b262-ec55a9c3244e
* Content: [Create an Azure Sphere tenant](https://docs.microsoft.com/en-us/azure-sphere/deployment/create-tenant)
* Content Source: [AzureSphere/articles/deployment/create-tenant.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/create-tenant.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by bawilless** [comment]
You may have more luck getting a response from the Microsoft Q&A Platform:  https://docs.microsoft.com/en-us/answers/index.html

Make sure you tag your post with Azure Sphere.

1. Did you migrate your tenant?  There were changes to the tenant last year that required older Azure Sphere Tenants to be migrated.  Documentation on migration is here:  https://docs.microsoft.com/en-us/answers/index.html.  Since you claimed your device before, it can't be used to create a new Azure Sphere tenant.

2. In my experience you likely have some kind of a driver issue where you're not able to connect to the device.  Sorry, I'm a Windows 10 user, so I can't help with the Ubuntu issue.  I'm working on building a Ubuntu box now so I can learn this path.  

I would check any connectivity issues on the system.  By the way, the recover command uses a different method to communicate to the device, it's a straight serial connection and uses a protocol like zmodem to transfer the files.  But normal communications is ethernet over serial, and this will trip you up if it's not working.  On windows it uses a TAP driver.

The other thing to try is make sure you're not connected to a VPN when you try to connect to your device.  Some VPN's disable "split tunneling" and that's required for the TAP driver to work (on windows).

Good luck

**Comment by nk-gears** [comment]
Thanks @bawilless 

@AshokPeddakotla-MSFT , I think you may be aware of this problem. 

I suspect the issue is because of the SDK Version which i used in Windows 10 vs SDK which is used in Ubuntu.

Should i need to use the same old SDK for migrating the tenant?. If thats the case, do we have old SDK for Ubuntu to migrate as i don't have a Windows 10 anymore.

Please help to resolve this.

**Comment by AshokPeddakotla-MSFT** [comment]
@nk-gears Could you please check this doc [About migration](https://docs.microsoft.com/en-us/azure-sphere/resources/rbac-device-migration) and let us know if you still need help.

**Comment by AshokPeddakotla-MSFT** [comment]
@nk-gears Yes you need ti use the old SDK to migrate. 

As mentioned in the doc, 

> Continue using the 19.09 SDK until you are ready to perform the migration. If you have already installed the 19.10 SDK but are not ready to migrate, uninstall it, then download the 19.09 SDK and reinstall it.
> 
> The 19.10 Azure Sphere SDK supports only the new user authentication and cloud management environment. After you install the 19.10 SDK, the only cloud-dependent azsphere command that you can use starts the migration process for a tenant. All other cloud-dependent commands will fail.

I would suggest you, Please file a support request @ https://aka.ms/azsupt? If you do not have access to a support plan, please reach out @ AZCommunity@microsoft.com with a link to this Issue as well as your subscription ID and we can help get the support ticket opened for this issue.

**Comment by nk-gears** [comment]
@AshokPeddakotla-MSFT Thanks for the detailed instructions.

Can you point me where to download the Azure Sphere 19.09 SDK for Ubuntu ?

**Comment by AshokPeddakotla-MSFT** [comment]
@nk-gears Sorry for the confusion around this. You should be able to perform migration with the current 20.07 Linux SDK (or any SDK from 19.10).  Indeed, the first Linux SDK wasn’t until 19.11!

https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk-linux?pivots=vs-code-linux

Please try with the current SDK and update. If you are still having the issue, as suggested, you can raise a request with support and the team will be able to help address the issue and provide the resolution accordingly.

**Comment by nk-gears** [comment]
When i try to migrate it prompts to login and after signing in using the same credentials.

AADSTS50020: User account 'myusername@live.in' from identity provider 'live.com' does not exist in tenant 'OsTechnology' and cannot access the application '0b1c8f7e-28d2-4378-97e2-7d7d63f7c87f'(Azure Sphere Utility) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account. Wondering who is "OsTechnology" ?

I will send mail to support. You can close this ticket. The above information is just  FYI.

**Comment by AshokPeddakotla-MSFT** [comment]
@nk-gears To provide more context, looks like you are using the personal MSA to login when attempting the migration.  But if you previously used Azure Sphere before the 19.10 migration, you must have signed up with an AAD organizational (work/school) account.  You should use that account to drive the migration.  The CLI prompts should instruct further on this. if that doesn't help and you are still struggling, please share get-support-data logs when you contact support. 

Since you are contacting support for further assistance, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by nk-gears** [comment]
Is there a way to identify to which Tenant my device is registered. Also i am seeing a tenant with the following name. Is this created by microsoft by default for all users?

![image](https://user-images.githubusercontent.com/897323/95441136-64b0d200-0977-11eb-8015-6e4eea7d5a8a.png)

**Comment by nk-gears** [comment]
I have added a TXT Entry to the DNS for hopechurch site. Please ask the client to test now.

![image](https://user-images.githubusercontent.com/897323/95442053-88284c80-0978-11eb-9804-40993104b36a.png)

**Comment by SatishBoddu-MSFT** [comment]
Hello @nk-gears Just checking back, could you please let us know if you need further help in this matter.

**Comment by nk-gears** [comment]
Yes. I need few clarifications.

How do I know which tenant the device was claimed ?.

I am a individual developer and I really don't remember the tenant which I claimed the device last year.

**Comment by SatishBoddu-MSFT** [comment]
Hi Nirmal,@nk-gears

Did you try the below commands from an AzSphere Dev CLI?

https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device#list

**azsphere device list**

https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-tenant#list

**azsphere tenant list**

ID                                   Name
--                                   ----
d343c263-4aa3-4558-adbb-d3fc34631800 Microsoft

![image](https://user-images.githubusercontent.com/62923178/96625994-bf292700-12c3-11eb-9ec1-58215c517aee.png)


One of our Microsoft MVP @matsujirushi [[profile](https://github.com/matsujirushi)]  developed this tool: **[Azure Sphere Explorer](https://github.com/matsujirushi/AzureSphereExplorer#azure-sphere-explorer)**
 
Please give it a try and let us know if it helps.

![image](https://user-images.githubusercontent.com/62923178/96626034-cea87000-12c3-11eb-9d31-c3c260b44348.png)

**Comment by SatishBoddu-MSFT** [comment]
We will update the outcome of the enabled support discussions soon.

**Comment by nk-gears** [comment]
@AshokPeddakotla-MSFT , Closing this Issue with resolved.

@SatishBoddu-MSFT , Thanks for working closely to troubleshoot the root cause and resolving them. I Appreciate the Team behind for the efforts and co-ordination.

Later i will share a detailed blog post on the scenario and how what are the things which i missed while migrating the device.

**Comment by arkesray** [comment]
> @AshokPeddakotla-MSFT , Closing this Issue with resolved.
> 
> @SatishBoddu-MSFT , Thanks for working closely to troubleshoot the root cause and resolving them. I Appreciate the Team behind for the efforts and co-ordination.
> 
> Later i will share a detailed blog post on the scenario and how what are the things which i missed while migrating the device.

Hi, I am having the same issue, can you please tell how to resolve? I can't migrate to the previous tenant, as it was 2 years ago.
![image](https://user-images.githubusercontent.com/26687445/124374882-5d2b1900-dcbc-11eb-8516-7f05ce92d5d9.png)

**Comment by nk-gears** [comment]
Hi @arkesray 

The Issue happened to me when i tried to Login using a different domain.

We need use similar to this "username@nirmalkumarlive.onmicrosoft.com". Then the issues resolved.

Please check what Directory you are trying to Login.
