### ISSUE TITLE
The Azure Sphere Security Service is not responding

### ISSUE THREAD

**Issue by niziak** [MicrosoftDocs/azure-sphere-issues#262]
Please add to page `azure-sphere/install/troubleshoot-installation#linux-specific-problems` workaround description for Debian Buster issue for following problem:

Trying to `azsphere login` responds with error:
`The Azure Sphere Security Service is not responding. Please check your network connection and try again`

The log file unveils error:
`Interop+Crypto+OpenSslCryptographicException: error:0E076071:configuration file routines:MODULE_RUN:unknown module name`

Workaround:

```bash
CLR_OPENSSL_VERSION_OVERRIDE=1.1 azsphere login
# or:
OPENSSL_CONF=/etc/ssl azsphere login
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859e405c-bdf9-0012-e6f8-706968193b40
* Version Independent ID: d5a03e55-b23b-2144-0045-492dca006b02
* Content: [Troubleshoot for Azure Sphere installation and setup](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation)
* Content Source: [AzureSphere/articles/install/troubleshoot-installation.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/troubleshoot-installation.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@niziak Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Please look into this feedback and update doc as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
I have assigned the issue to the content author @pennyo to evaluate and update the doc as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
@niziak We really appreciate for reporting the issue and providing the fix. It will definitely beneficial to the other community members. 

We see that the problem occurs on Debian Buster Linux, whereas we support Ubuntu 20.04. We haven’t repro'd the error on the supported Ubuntu. If we find that it’s a common problem to several Linux flavors, we would consider adding it to the documentation, currently we will not be able to document for every flavor of Linux, or to test them.

I Would suggest you, please post this solution on the [Microsoft Q&A forum](https://docs.microsoft.com/en-us/answers/topics/azure-sphere.html) for broader visibility so that others can also find your solution. 

We agree that it’s useful.  We’re just pretty sure the documentation isn’t the place for it, as it’s an unsupported scenario. Thanks again for providing the feedback and we really appreciate your valuable suggestions.

Thanks for your understanding. Do let us know if you have any further queries. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
