### ISSUE TITLE
Missing one line before Install-Module AzureAD

### ISSUE THREAD

**Issue by blkknight01** [MicrosoftDocs/azure-sphere-issues#288]
Should have users run this command in Powershell first: This allows for the find and installation of Nuget
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36b86d1-7863-0e97-b628-6a9c09d37002
* Version Independent ID: 0999270f-e254-31da-37d8-9e05f99fec40
* Content: [Authentication overview - Azure Sphere Public API](https://docs.microsoft.com/en-us/azure-sphere/deployment/authenticate-options)
* Content Source: [AzureSphere/articles/deployment/authenticate-options.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/authenticate-options.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by AshokPeddakotla-MSFT** [comment]
.

**Comment by SatishBoddu-MSFT** [comment]
Hello @blkknight01 Thanks for reaching out on this page, we appreciate your contribution!

**Install-Module AzureAD** itself is sufficient to find and install the module from the PowerShell Gallery. If this is not helping or giving any error, then please let us know.

![image](https://user-images.githubusercontent.com/62923178/145452086-522b058c-221d-4757-8f09-8233a0ae2671.png)

![image](https://user-images.githubusercontent.com/62923178/145453116-e0029f1f-7d21-4c55-a682-734403e93c11.png)


**Coming to the reported issue subject:**
_[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12_
**IMHO**: This command will force the use of TLS 1.2 (you can also make it use 1.1 if you want for some reason).

Could you please let us know the PowerShell documentation on this command for the need to be added before installing any module? that would be very helpful to us to better prioritize this request. If we are NOT blocked by NOT using this command, then do let us know so that we will close this issue. Happy to help further!

**Comment by AshokPeddakotla-MSFT** [comment]
@blkknight01 Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
