### ISSUE TITLE
Exception when adding Iot Hub Service in Visual Studio 

### ISSUE THREAD

**Issue by HowardEdidin** [MicrosoftDocs/azure-sphere-issues#41]
![iotissue](https://user-images.githubusercontent.com/19954905/46892682-f2629100-ce33-11e8-952a-98d6315cc7b7.png)

**Comment by Mike-Ubezzi-MSFT** [comment]
@HowardEdidin Can you please use the following [Microsoft Visual Studio and .NET Framework Log Collection Tool](https://www.microsoft.com/en-us/download/details.aspx?id=12493) and send the output to AzCommunity at Microsoft.com, so that we can investigate this further. Thank you!

**Comment by Mike-Ubezzi-MSFT** [comment]
@HowardEdidin The below steps can be followed if you need to be unblocked now. We have a couple repro steps to confirm but we think it is related to an install sequence of the public extension was installed either before the Azure Sphere SDK or after it was installed. This is being investigated.

•	Uninstall the Azure Sphere VS SDK
•	Open VS, check to see if there is a Connected Service for Azure IoT Hub present, if so remove it.

![az_iot_vs_ext](https://user-images.githubusercontent.com/37126106/47249970-57d3f600-d3cf-11e8-85c6-9d16f23353d7.png)

•	Reinstall the Azure Sphere SDK.
•	Do not install the Azure IoT Hub extension again, use the one that was included in the Azure Sphere SDK

If you need that extension because it supports C#, wait for our investigation to conclude to get further advice. Thank you, Mike

**Comment by HowardEdidin** [comment]
Weird that I have two

[cid:image001.png@01D467F7.B960D120]

**Comment by HowardEdidin** [comment]
Only one was uninstalled.

I tried installing the SDK again. Same error.

**Comment by AshokPeddakotla-MSFT** [comment]
@HowardEdidin Sorry for the delayed respoinse. Could you please use the latest version of SDK and let us know if you still see the error message.

**Comment by HowardEdidin** [comment]
I did a complete reinstall and it works now.

**Comment by AshokPeddakotla-MSFT** [comment]
@HowardEdidin Glad to hear that your issue is resolved. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
