### ISSUE TITLE
WIFI RSSI problem

### ISSUE THREAD

**Issue by rickeycv** [MicrosoftDocs/azure-sphere-issues#94]
Hi,
I'm trying to get RSSI level using this function but I always get RSSI = 0. Is there a problem with the API?
When I call "azsphere device wifi scan" in the command prompt window I can get signal levels without problems.
Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12330c3e-8ed0-61f1-21c1-4338cdbf90ba
* Version Independent ID: 079cd516-7143-cf46-f67b-2df521a80028
* Content: [WifiConfig_GetCurrentNetwork function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-wificonfig/function-wificonfig-getcurrentnetwork#feedback)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-wificonfig/function-wificonfig-getcurrentnetwork.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-wificonfig/function-wificonfig-getcurrentnetwork.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@rickeycv Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by sergaz-msft** [comment]
Hi @rickeycv is this the same issue as the one reported on MSDN? https://social.msdn.microsoft.com/Forums/en-US/0c9b56ee-4498-423f-9f31-c71363f73e30/api-bug-wificonfiggetcurrentnetwork-function-always-returns-rssi-value-of-zero-via?forum=azuresphere

Thanks!

**Comment by rickeycv** [comment]
The returned value of WifiConfig_GetCurrentNetwork function is zero of course, that is why I can get SSID and Frequency without problems. The problem is in the pointer to WifiConfig_ConnectedNetwork struct, one of the fields of WifiConfig_ConnectedNetwork struct is the RSSI value, which always is zero. WifiConfig_TriggerScanAndGetScannedNetworkCount() and WifiConfig_GetScannedNetworks() functions however, both return a valid RSSI value (via WifiConfig_ScannedNetwork struct).

**Comment by sergaz-msft** [comment]
Sorry for the misunderstanding and thanks for providing more details.
I will check on my side if I have the same behavior. In the meantime please let us know the SDK and OS Version?

- azsphere show-version

- azsphere device show-ota-status

Thanks,

**Comment by rickeycv** [comment]
azsphere show-version:
19.02
azsphere device show-ota-status:
19.04

Thanks.

**Comment by sergaz-msft** [comment]
Thank you! I was also able to repro this issue on 19.04. I checked with Product Group and this is known. I am now trying to confirm if it is fixed on 19.05. If you can report the RSSI value on a D2C message to Azure IoT can you test it using the Eval Feed with 19.05 version? The reason I ask you to test it with Azure IoT is because you can't debug a device with an Eval Feed on it.

Thanks

**Comment by rickeycv** [comment]
Thank you, I was testing my code using Eval Feed with 19.05 version and now I am able to get the RSSI value. When 19.05 version is going to be released?

**Comment by sergaz-msft** [comment]
Glad that you could verify that the bug is fixed on 19.05 version. As explained [here](https://docs.microsoft.com/en-us/azure-sphere/deployment/deployment-microsoft-feeds) The Retail Evaluation Azure Sphere OS feed provides OS software **14 days before** its release to the Retail Azure Sphere OS feed. Therefore the Retail feed should be receiving the new version between today or tomorrow.

Thanks!

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
